name: place_me
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.1
  # Sign-in with Google
  google_sign_in: ^5.4.0
  sign_in_with_apple: ^5.0.0
  firebase_storage: 12.4.4

  # File and image pickers
  image_picker: ^0.8.7
  intl: ^0.18.0
  charset_converter: ^2.0.1

  # UI
  lottie: ^3.3.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  permission_handler: ^10.4.0
  file_selector: ^1.0.3
  csv: ^5.0.1
  excel: 4.0.6
  path_provider: ^2.0.11
  rxdart: ^0.27.7

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
  fonts:
    - family: DanhDa
      fonts:
        - asset: fonts/DanhDa-Bold.otf
    - family: Satreva
      fonts:
        - asset: fonts/Satreva.ttf
    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf