name: place_me
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.12.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  # Sign-in with Google
  google_sign_in: ^6.2.2

  # File and image pickers
  image_picker: ^0.8.7



  # UI
  lottie: ^3.3.0
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
  fonts:
    - family: DanhDa
      fonts:
        - asset: fonts/DanhDa-Bold.otf
    - family: Satreva
      fonts:
        - asset: fonts/Satreva.ttf
    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
