name: place_me
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
    android: true
    ios: true
    image_path: "images/PlaceMe.png"

flutter_test:
  sdk: flutter


flutter_lints: ^5.0.0

flutter:
  assets:
    - images/
  fonts:
    - family: DanhDa
      fonts:
        - asset: fonts/DanhDa-Bold.otf
    - family: Satreva
      fonts:
        - asset: fonts/Satreva.ttf
    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf

