name: Test Minimal CI

on:
  push:
    branches:
      - main
      - Sprint1-Neria
      - sprint1-Nativ


jobs:
  test-minimal:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Test
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: README.md
